#!bin/sh

/etc/init.d/dnode

/bin/echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

mount -t squashfs /dev/mtdblock3 /usr   
mount -t squashfs /dev/mtdblock4 /mnt/web
mount -t squashfs /dev/mtdblock5 /mnt/custom
mount -t cramfs /dev/mtdblock6 /mnt/logo
mount -t jffs2 /dev/mtdblock7 /mnt/mtd
if [ $? -ne 0 ];then
        echo "Clean up the old data in the 'mtd' partition."
        /sbin/flash_eraseall -j -q /dev/mtd7 
        mount -t jffs2 /dev/mtdblock7 /mnt/mtd
fi

mount -t ramfs  /dev/mem        /var
mkdir -p /var/tmp

mount -t ramfs  /dev/mem        /tmp

mkdir -p /mnt/mtd/Config /mnt/mtd/Log /mnt/mtd/Config/ppp /mnt/mtd/Config/Json

echo 655360 > /proc/sys/net/core/rmem_max